import "~/styles/globals.css";

import { Inter as FontSans } from "next/font/google";

import { ThemeProvider } from "~/components/theme-provider";
import { cn } from "~/lib/utils";
import { TRPCReactProvider } from "~/trpc/react";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Cube X",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo_white.svg" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable,
        "font-degular",
      )}
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem >
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
